BEGIN TRY
    BEGIN TRANSACTION

        INSERT INTO ProductosXML VALUES (7 ,'XD')
        INSERT INTO ProductosXML VALUES (8 ,'XD')
        INSERT INTO ProductosXML VALUES (11,'XD')
        INSERT INTO ProductosXML VALUES (7,'XD')

    COMMIT TRANSACTION
END TRY
BEGIN CATCH

    ROLLBACK TRANSACTION

    DECLARE @ERROR_MESSAGE VARCHAR(MAX)
    DECLARE @ERROR_SEVERITY INT
    DECLARE @ERROR_STATE INT

    SELECT 
        @ERROR_MESSAGE = ERROR_MESSAGE(),
        @ERROR_SEVERITY = ERROR_SEVERITY(),
        @ERROR_STATE = ERROR_STATE()

    RAISERROR(@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE)
END CATCH